# Generated by Django 5.2.17 on 2026-09-08 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(default='09ABUCS7544P1Z2', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Invalid GSTIN format.')])),
                ('rate_percent', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100)])),
                ('supply_description', models.CharField(default='IT software product and services', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'GST configuration',
            },
        ),
    ]
