# Generated by Django 5.2.17 on 2026-08-31 09:07

import django.db.models.deletion
import uuid
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='videos/thumbnails/')),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('hls', 'HLS'), ('file', 'File'), ('vimeo', 'Vimeo')], max_length=32)),
                ('video_url', models.URLField(blank=True, validators=[videos.models.validate_safe_stream_url])),
                ('video_file', models.FileField(blank=True, upload_to='videos/files/')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-published_at'], name='videos_vide_tenant__70d62b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_video_slug_per_tenant')],
            },
        ),
    ]
