# Generated by Django 5.2.17 on 2026-08-31 08:46

import core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('publication_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('dark_logo', models.ImageField(blank=True, upload_to='branding/')),
                ('mobile_logo', models.ImageField(blank=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#1f2937', max_length=7)),
                ('secondary_color', models.CharField(default='#0f766e', max_length=7)),
                ('accent_color', models.CharField(default='#dc2626', max_length=7)),
                ('typography', core.fields.JSONTextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('contact_details', core.fields.JSONTextField(blank=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('social_urls', core.fields.JSONTextField(blank=True)),
                ('header_style', models.CharField(choices=[('classic', 'Classic'), ('compact', 'Compact'), ('centered', 'Centered')], default='classic', max_length=32)),
                ('footer_style', models.CharField(choices=[('simple', 'Simple'), ('columns', 'Columns'), ('editorial', 'Editorial')], default='columns', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_branding_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ThemeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('active_theme', models.CharField(choices=[('theme_classic', 'Classic'), ('theme_modern', 'Modern'), ('theme_tv', 'TV')], default='theme_classic', max_length=40)),
                ('draft_theme', models.CharField(choices=[('theme_classic', 'Classic'), ('theme_modern', 'Modern'), ('theme_tv', 'TV')], default='theme_classic', max_length=40)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_theme_activation_per_tenant')],
            },
        ),
    ]
