# Generated by Django 5.2.17 on 2026-08-31 08:35

import core.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('photo', models.ImageField(blank=True, upload_to='authors/')),
                ('bio', models.TextField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=160)),
                ('social_links', core.fields.JSONTextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('short_description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='articles/')),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_breaking', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('is_editor_pick', models.BooleanField(db_index=True, default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('focus_keyword', models.CharField(blank=True, max_length=160)),
                ('canonical_override', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.authorprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='categories.category')),
                ('reporters', models.ManyToManyField(blank=True, related_name='reported_articles', to='news.authorprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('ticker_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaking_items', to='news.newsarticle')),
            ],
            options={
                'ordering': ['ticker_order', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.tag'),
        ),
        migrations.AddIndex(
            model_name='authorprofile',
            index=models.Index(fields=['tenant', 'is_public'], name='news_author_tenant__9c667a_idx'),
        ),
        migrations.AddIndex(
            model_name='authorprofile',
            index=models.Index(fields=['tenant', 'display_name'], name='news_author_tenant__a70f89_idx'),
        ),
        migrations.AddConstraint(
            model_name='authorprofile',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_author_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='breakingnews',
            index=models.Index(fields=['tenant', 'is_active', 'ticker_order'], name='news_breaki_tenant__b9d527_idx'),
        ),
        migrations.AddIndex(
            model_name='breakingnews',
            index=models.Index(fields=['tenant', 'starts_at', 'ends_at'], name='news_breaki_tenant__e06e58_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tenant', 'is_active'], name='news_tag_tenant__69d21b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_tag_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'status', '-published_at'], name='news_newsar_tenant__eaf236_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'category', 'status'], name='news_newsar_tenant__475feb_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'is_breaking', 'status'], name='news_newsar_tenant__7d1526_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'is_featured', 'status'], name='news_newsar_tenant__71a089_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'is_trending', 'status'], name='news_newsar_tenant__9b69b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsarticle',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_article_slug_per_tenant'),
        ),
    ]
