# Generated by Django 5.2.17 on 2026-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('news', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='content_type',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog')], db_index=True, default='news', max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['tenant', 'content_type', 'status', '-published_at'], name='news_newsar_tenant__86e38b_idx'),
        ),
    ]
