# Generated by Django 5.2.17 on 2026-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
