# Generated by Django 5.2.17 on 2026-09-19 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_district'),
        ('tenants', '0003_tenant_customer_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('location_type', models.CharField(choices=[('district', 'District'), ('city', 'City')], db_index=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['state', 'district', 'name'],
                'indexes': [models.Index(fields=['tenant', 'location_type', 'country', 'state'], name='news_newslo_tenant__5b9b78_idx'), models.Index(fields=['tenant', 'location_type', 'district'], name='news_newslo_tenant__0deaf4_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'location_type', 'country', 'state', 'district', 'name'), name='unique_news_location_per_tenant')],
            },
        ),
    ]
