# Generated by Django 5.2.17 on 2026-08-31 09:07

import django.db.models.deletion
import uuid
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTVChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube Live'), ('hls', 'HLS')], max_length=32)),
                ('stream_url', models.URLField(validators=[videos.models.validate_safe_stream_url])),
                ('poster_image', models.ImageField(blank=True, upload_to='livetv/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='livetv_live_tenant__43b986_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_livetv_slug_per_tenant')],
            },
        ),
    ]
