# Generated by Django 5.2.17 on 2026-08-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livetv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livetvchannel',
            options={'ordering': ['name', 'id']},
        ),
    ]
