# Generated by Django 5.2.17 on 2026-08-31 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('news', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('path', models.CharField(max_length=500)),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='news.newsarticle')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='categories.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='analytics_p_tenant__8872a0_idx'), models.Index(fields=['tenant', 'article', 'occurred_at'], name='analytics_p_tenant__803536_idx'), models.Index(fields=['tenant', 'category', 'occurred_at'], name='analytics_p_tenant__60c06d_idx')],
            },
        ),
    ]
