# Generated by Codex on 2026-09-04

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='unique_visitor_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='pageview',
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(('article__isnull', False), ('unique_visitor_key__gt', '')),
                fields=('tenant', 'article', 'unique_visitor_key'),
                name='unique_article_view_per_visitor',
            ),
        ),
    ]
