# Generated by Django 3.2.25 on 2026-08-31 08:18

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('publication_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='trial', max_length=32)),
                ('onboarding_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=32)),
                ('default_language', models.CharField(default='en', max_length=16)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Tenant Owner'), ('administrator', 'Administrator'), ('editor', 'Editor'), ('reporter', 'Reporter'), ('seo_manager', 'SEO Manager'), ('advertisement_manager', 'Advertisement Manager')], max_length=40)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], db_index=True, default='invited', max_length=32)),
                ('permissions', core.fields.JSONTextField(blank=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'role', 'status'], name='tenants_ten_tenant__33b3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'status'], name='tenants_ten_user_id_21c5a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_tenant_user_membership'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug', 'status'], name='tenants_ten_slug_2439c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['owner', 'status'], name='tenants_ten_owner_i_6201a8_idx'),
        ),
    ]
