# Generated by Django 5.2.17 on 2026-09-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_customer_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('header_rectangle', 'Header rectangle - 970 x 250 recommended'), ('after_hero_rectangle', 'After top story - 970 x 250 recommended'), ('sidebar_square', 'Sidebar square - 300 x 300 recommended')], db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='tenant-ads/')),
                ('target_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='tenants.tenant')),
            ],
            options={
                'ordering': ['placement', 'display_order', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'placement', 'is_active'], name='tenants_ten_tenant__82773d_idx')],
            },
        ),
    ]
