# Generated by Django 5.2.17 on 2026-08-31 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms'), ('disclaimer', 'Disclaimer'), ('editorial_policy', 'Editorial Policy'), ('corrections_policy', 'Corrections Policy'), ('ethics_policy', 'Ethics Policy'), ('advertise', 'Advertise With Us'), ('custom', 'Custom Page')], db_index=True, default='custom', max_length=40)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['tenant', 'page_type'], name='pages_page_tenant__288946_idx'), models.Index(fields=['tenant', 'is_published'], name='pages_page_tenant__6de1ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_page_slug_per_tenant')],
            },
        ),
    ]
