# Generated by Django 5.2.17 on 2026-08-31 08:46

import core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('pages', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Homepage', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=32)),
                ('theme_key', models.CharField(default='theme_classic', max_length=40)),
                ('published_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_restores', to='pages.homepagelayout')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('block_type', models.CharField(choices=[('breaking_news', 'Breaking News Ticker'), ('hero_news', 'Hero News'), ('latest_news', 'Latest News'), ('category_news', 'Category News'), ('news_grid', 'News Grid'), ('news_list', 'News List'), ('trending', 'Trending'), ('editor_picks', 'Editor Picks'), ('videos', 'Videos'), ('live_tv', 'Live TV'), ('photo_gallery', 'Photo Gallery'), ('advertisement', 'Advertisement'), ('custom_content', 'Custom Content')], max_length=40)),
                ('heading', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('article_count', models.PositiveIntegerField(default=6)),
                ('layout_variant', models.CharField(default='standard', max_length=60)),
                ('show_image', models.BooleanField(default=True)),
                ('show_description', models.BooleanField(default=True)),
                ('desktop_columns', models.PositiveIntegerField(default=3)),
                ('settings', core.fields.JSONTextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homepage_blocks', to='categories.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.homepagelayout')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('link_type', models.CharField(choices=[('home', 'Home'), ('category', 'Category'), ('page', 'Page'), ('videos', 'Videos'), ('live_tv', 'Live TV'), ('external', 'External Link')], max_length=32)),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='categories.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.menu')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('settings', core.fields.JSONTextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['tenant', 'order'], name='pages_foote_tenant__bd1f36_idx'), models.Index(fields=['tenant', 'is_enabled'], name='pages_foote_tenant__9fc6b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='homepagelayout',
            index=models.Index(fields=['tenant', 'status'], name='pages_homep_tenant__f41339_idx'),
        ),
        migrations.AddConstraint(
            model_name='homepagelayout',
            constraint=models.UniqueConstraint(fields=('tenant', 'status'), name='unique_homepage_layout_status_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='homepageblock',
            index=models.Index(fields=['tenant', 'layout', 'order'], name='pages_homep_tenant__ee1eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='homepageblock',
            index=models.Index(fields=['tenant', 'block_type', 'is_enabled'], name='pages_homep_tenant__f2cbe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('tenant', 'location'), name='unique_menu_location_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['tenant', 'menu', 'parent', 'order'], name='pages_menui_tenant__27a2cb_idx'),
        ),
    ]
