from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "output" / "pdf"
OUTPUT.mkdir(parents=True, exist_ok=True)

FONT_REGULAR = "Helvetica"
FONT_BOLD = "Helvetica-Bold"
for candidate in [
    Path("C:/Windows/Fonts/Nirmala.ttc"),
    Path("C:/Windows/Fonts/Nirmala.ttf"),
    Path("C:/Windows/Fonts/mangal.ttf"),
    Path("C:/Windows/Fonts/arialuni.ttf"),
]:
    if candidate.exists():
        pdfmetrics.registerFont(TTFont("Devanagari", str(candidate)))
        FONT_REGULAR = "Devanagari"
        FONT_BOLD = "Devanagari"
        break


def money(value):
    return f"INR {value:,.2f}"


def build_invoice(path, lang):
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
    )
    styles = getSampleStyleSheet()
    body_font = FONT_REGULAR if lang == "hi" else "Helvetica"
    bold_font = FONT_BOLD if lang == "hi" else "Helvetica-Bold"
    styles.add(ParagraphStyle(name="Brand", fontName=bold_font, fontSize=22, leading=27, textColor=colors.HexColor("#0f3b31")))
    styles.add(ParagraphStyle(name="TitleRight", fontName=bold_font, fontSize=20, leading=25, alignment=TA_RIGHT, textColor=colors.HexColor("#0f3b31")))
    styles.add(ParagraphStyle(name="SmallMuted", fontName=body_font, fontSize=8.5, leading=12, textColor=colors.HexColor("#5f7169")))
    styles.add(ParagraphStyle(name="BodyLocal", fontName=body_font, fontSize=10.5, leading=15, textColor=colors.HexColor("#17231f")))
    styles.add(ParagraphStyle(name="BoldLocal", fontName=bold_font, fontSize=10.5, leading=15, textColor=colors.HexColor("#17231f")))
    styles.add(ParagraphStyle(name="Section", fontName=bold_font, fontSize=12.5, leading=16, textColor=colors.HexColor("#0f3b31")))

    if lang == "hi":
        invoice_title = "नमूना इनवॉइस"
        invoice_note = "यह Press Nexa द्वारा प्रदर्शन और परीक्षण के लिए बनाया गया नमूना इनवॉइस है। यह किसी वास्तविक भुगतान का टैक्स इनवॉइस नहीं है।"
        billed_to = "ग्राहक विवरण"
        payment_details = "भुगतान विवरण"
        item_title = "सेवा विवरण"
        total_label = "कुल राशि"
        footer = "Press Nexa - SHRI INFOWAVE PRIVATE LIMITED | CIN: U62012UW2026PTC257361 | PAN: ABUCS7544P"
        rows = [
            ["विवरण", "अवधि", "राशि"],
            ["Press Nexa News + Video SaaS Plan", "Monthly", money(999.00)],
            ["Tenant workspace setup and onboarding access", "Included", money(0.00)],
        ]
        customer_lines = [
            "Publication: Demo News Portal",
            "Username: demo_news_8396",
            "Mobile: 8279408396",
            "Email: customer@example.com",
        ]
        payment_lines = [
            "Payment status: Successful",
            "Payment ID: pay_TEST123456789",
            "Order ID: order_TEST123456",
            "Invoice No: PN-DUMMY-2026-001",
            "Invoice Date: 03 September 2026",
        ]
    else:
        invoice_title = "Sample Invoice"
        invoice_note = "This sample invoice is generated by Press Nexa for demonstration and testing. It is not a tax invoice for an actual payment."
        billed_to = "Customer Details"
        payment_details = "Payment Details"
        item_title = "Service Details"
        total_label = "Total Amount"
        footer = "Press Nexa - SHRI INFOWAVE PRIVATE LIMITED | CIN: U62012UW2026PTC257361 | PAN: ABUCS7544P"
        rows = [
            ["Description", "Period", "Amount"],
            ["Press Nexa News + Video SaaS Plan", "Monthly", money(999.00)],
            ["Tenant workspace setup and onboarding access", "Included", money(0.00)],
        ]
        customer_lines = [
            "Publication: Demo News Portal",
            "Username: demo_news_8396",
            "Mobile: 8279408396",
            "Email: customer@example.com",
        ]
        payment_lines = [
            "Payment status: Successful",
            "Payment ID: pay_TEST123456789",
            "Order ID: order_TEST123456",
            "Invoice No: PN-DUMMY-2026-001",
            "Invoice Date: 03 September 2026",
        ]

    story = []
    header = Table(
        [
            [
                Paragraph("Press Nexa", styles["Brand"]),
                Paragraph(invoice_title, styles["TitleRight"]),
            ],
            [
                Paragraph(
                    "Operated by SHRI INFOWAVE PRIVATE LIMITED<br/>"
                    "101 Govind Kund Tila, Radha Niwas, Vrindaban, Mathura - 281121, Uttar Pradesh, India<br/>"
                    "Support: srbc500@gmail.com | WhatsApp: 8279408396",
                    styles["SmallMuted"],
                ),
                Paragraph("Amount<br/><b>INR 999.00</b>", styles["TitleRight"]),
            ],
        ],
        colWidths=[105 * mm, 54 * mm],
    )
    header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
    story.append(header)
    story.append(Spacer(1, 12))
    story.append(Paragraph(invoice_note, styles["BodyLocal"]))
    story.append(Spacer(1, 16))

    details = Table(
        [
            [
                Paragraph(f"<b>{billed_to}</b><br/>" + "<br/>".join(customer_lines), styles["BodyLocal"]),
                Paragraph(f"<b>{payment_details}</b><br/>" + "<br/>".join(payment_lines), styles["BodyLocal"]),
            ]
        ],
        colWidths=[78 * mm, 78 * mm],
    )
    details.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#eef6f2")),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#cfe0d8")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cfe0d8")),
        ("PADDING", (0, 0), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(details)
    story.append(Spacer(1, 18))
    story.append(Paragraph(item_title, styles["Section"]))
    story.append(Spacer(1, 8))

    item_table = Table(rows, colWidths=[95 * mm, 32 * mm, 32 * mm])
    item_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f3b31")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), body_font),
        ("FONTNAME", (0, 0), (-1, 0), bold_font),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#cfe0d8")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e6df")),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (2, 1), (2, -1), "RIGHT"),
    ]))
    story.append(item_table)
    story.append(Spacer(1, 12))
    total = Table([[Paragraph(f"<b>{total_label}</b>", styles["BoldLocal"]), Paragraph("<b>INR 999.00</b>", styles["BoldLocal"])]], colWidths=[120 * mm, 39 * mm])
    total.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f6faf8")),
        ("BOX", (0, 0), (-1, -1), 0.75, colors.HexColor("#cfe0d8")),
        ("PADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
    ]))
    story.append(total)
    story.append(Spacer(1, 22))
    story.append(Paragraph("Profile URL: https://pressnexa.live-app.in/account/profile/", styles["BodyLocal"]))
    story.append(Paragraph("Onboarding URL: https://pressnexa.live-app.in/billing/onboarding/", styles["BodyLocal"]))
    story.append(Spacer(1, 22))
    story.append(Paragraph(footer, styles["SmallMuted"]))
    doc.build(story)


if __name__ == "__main__":
    build_invoice(OUTPUT / "pressnexa-sample-invoice-english.pdf", "en")
    build_invoice(OUTPUT / "pressnexa-sample-invoice-hindi.pdf", "hi")
    print(OUTPUT)
