# Generated by Django 5.2.17 on 2026-08-31 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPaperEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('publication_date', models.DateField()),
                ('edition_name', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('pdf_file', models.FileField(upload_to='epaper/pdfs/')),
                ('cover_image', models.ImageField(blank=True, upload_to='epaper/covers/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=40)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epaper_editions', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-publication_date', '-created_at'),
                'indexes': [models.Index(fields=['tenant', 'status', 'publication_date'], name='epaper_epap_tenant__a3d7e2_idx'), models.Index(fields=['tenant', 'city', 'region'], name='epaper_epap_tenant__e01842_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_tenant_epaper_slug')],
            },
        ),
    ]
