# Generated by Django 5.2.17 on 2026-09-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPaperPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='epaper/pages/')),
                ('mobile_image', models.ImageField(upload_to='epaper/pages/')),
                ('zoom_image', models.ImageField(upload_to='epaper/pages/')),
                ('thumbnail', models.ImageField(upload_to='epaper/pages/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='epaper.epaperedition')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'number'), name='unique_epaper_page_number')],
            },
        ),
    ]
