# Generated by Django 5.2.17 on 2026-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0002_epaperpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaperedition',
            name='processing_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epaperedition',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epaperedition',
            name='processing_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='epaperedition',
            name='processing_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epaperedition',
            name='processing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
