# Generated by Django 5.2.17 on 2026-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0003_epaperedition_processing_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaperpage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='epaper/pages/'),
        ),
        migrations.AlterField(
            model_name='epaperpage',
            name='mobile_image',
            field=models.ImageField(max_length=500, upload_to='epaper/pages/'),
        ),
        migrations.AlterField(
            model_name='epaperpage',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to='epaper/pages/'),
        ),
        migrations.AlterField(
            model_name='epaperpage',
            name='zoom_image',
            field=models.ImageField(max_length=500, upload_to='epaper/pages/'),
        ),
    ]
