# Generated by Django 5.2.17 on 2026-08-31 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('menu_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('homepage_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['menu_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'parent', 'menu_order'], name='categories__tenant__c66eaf_idx'), models.Index(fields=['tenant', 'is_active', 'show_in_menu'], name='categories__tenant__ab0088_idx'), models.Index(fields=['tenant', 'is_active', 'show_on_homepage'], name='categories__tenant__86a196_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_category_slug_per_tenant')],
            },
        ),
    ]
