# Generated by Django 5.2.17 on 2026-09-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Press Nexa 365', max_length=120, unique=True)),
                ('starts_on', models.DateField()),
                ('days', models.PositiveSmallIntegerField(default=365)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('language', models.CharField(choices=[('hi', 'हिंदी'), ('en', 'English')], max_length=2)),
                ('topic', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting content'), ('ready', 'Ready to publish'), ('published', 'Published'), ('hold', 'Editorial hold')], db_index=True, default='pending', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='publisher_blog.campaign')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'scheduled_at'), name='unique_marketing_slot')],
            },
        ),
    ]
