# Generated by Django 5.2.17 on 2026-08-31 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(choices=[('homepage_top', 'Homepage Top'), ('homepage_middle', 'Homepage Middle'), ('article_top', 'Article Top'), ('article_middle', 'Article Middle'), ('article_bottom', 'Article Bottom'), ('sidebar', 'Sidebar'), ('category', 'Category'), ('mobile', 'Mobile')], max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='ads/')),
                ('destination_url', models.URLField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertisements.adcampaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='advertisements.adplacement')),
            ],
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['tenant', 'is_active', 'starts_at', 'ends_at'], name='advertiseme_tenant__f817fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='adplacement',
            constraint=models.UniqueConstraint(fields=('tenant', 'position', 'name'), name='unique_ad_placement_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['tenant', 'placement', 'is_active'], name='advertiseme_tenant__04e73d_idx'),
        ),
    ]
