# Generated by Django 5.2.17 on 2026-08-31 09:13

import core.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcreative',
            name='image',
            field=models.ImageField(upload_to=core.security.safe_upload_name, validators=[core.security.validate_upload_file]),
        ),
    ]
