# Generated by Django 3.2.25 on 2026-08-31 08:18

from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('platform_subdomain', 'Platform Subdomain'), ('custom_domain', 'Custom Domain')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verification_token', models.CharField(default=secrets.token_urlsafe, max_length=96)),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT'), ('file', 'File'), ('cname', 'CNAME')], default='dns_txt', max_length=32)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['domain', 'status'], name='domains_ten_domain_4e32e0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant', 'domain_type'], name='domains_ten_tenant__303203_idx'),
        ),
    ]
