# Generated by Django 5.2.17 on 2026-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdomain',
            name='ssl_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='ssl_provisioning_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='ssl_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('failed', 'Failed'), ('renewing', 'Renewing')], default='pending', max_length=32),
        ),
    ]
