# Generated by Django 5.2.17 on 2026-08-31 09:01

import core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business')], max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entitlements', core.fields.JSONTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('refund', 'Refund/Cancellation Policy'), ('billing', 'Subscription/Billing Policy'), ('contact', 'Contact'), ('grievance', 'Support/Grievance Information')], max_length=40, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.plan')),
            ],
        ),
        migrations.CreateModel(
            name='RazorpayPlanMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=10)),
                ('razorpay_plan_id', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_mappings', to='subscriptions.planprice')),
            ],
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('payment_issue', 'Payment Issue'), ('grace_period', 'Grace Period'), ('restricted', 'Restricted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='trial', max_length=40)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('charge_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_subscriptions', to='subscriptions.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('razorpay_invoice_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(db_index=True, max_length=60)),
                ('payload', core.fields.JSONTextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.tenant')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='subscriptions.tenantsubscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=10)),
                ('provider', models.CharField(default='razorpay', max_length=40)),
                ('event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', core.fields.JSONTextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'environment', 'event_id'), name='unique_provider_webhook_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(fields=('plan', 'billing_cycle'), name='unique_plan_billing_cycle'),
        ),
        migrations.AddConstraint(
            model_name='razorpayplanmapping',
            constraint=models.UniqueConstraint(fields=('environment', 'razorpay_plan_id'), name='unique_razorpay_plan_environment'),
        ),
    ]
