# Generated by Django 5.2.17 on 2026-08-31 10:11

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration_json', core.fields.JSONTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('feature_type', models.CharField(choices=[('boolean', 'Boolean'), ('limit', 'Limit'), ('configuration', 'Configuration')], default='boolean', max_length=20)),
                ('default_unit', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration_json', core.fields.JSONTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_type', models.CharField(choices=[('grant', 'Grant'), ('restrict', 'Restrict'), ('configure', 'Configure')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('configuration_json', core.fields.JSONTextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('business', 'Business'), ('news_starter', 'News Starter'), ('news_video', 'News + Video'), ('news_pro', 'News Pro'), ('news_business', 'News Business')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_plan_code_version'),
        ),
        migrations.AddField(
            model_name='addon',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='add_ons', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_add_ons', to='subscriptions.addon'),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantfeatureoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantfeatureoverride',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='tenantfeatureoverride',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='planfeature',
            index=models.Index(fields=['plan', 'is_enabled'], name='subscriptio_plan_id_54c7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='planfeature',
            index=models.Index(fields=['feature', 'is_enabled'], name='subscriptio_feature_201a49_idx'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature'),
        ),
        migrations.AddIndex(
            model_name='tenantaddon',
            index=models.Index(fields=['tenant', 'is_active'], name='subscriptio_tenant__a553c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantaddon',
            index=models.Index(fields=['starts_at', 'expires_at'], name='subscriptio_starts__b6b0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['tenant', 'feature', 'override_type'], name='subscriptio_tenant__b3cf01_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantfeatureoverride',
            index=models.Index(fields=['starts_at', 'expires_at'], name='subscriptio_starts__92a398_idx'),
        ),
    ]
