# Generated by Django 5.2.17 on 2026-08-31 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_addon_feature_planfeature_tenantaddon_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='addon',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addon',
            name='monthly_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addon',
            name='razorpay_monthly_plan_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='addon',
            name='razorpay_yearly_plan_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='addon',
            name='yearly_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='limit_override',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='provider_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantaddon',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('payment_pending', 'Payment Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=40),
        ),
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('change_type', models.CharField(choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('verified', 'Verified'), ('scheduled', 'Scheduled'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=40)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_plan_changes', to='subscriptions.plan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to='tenants.tenant')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_plan_changes', to='subscriptions.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('onboarding', 'Onboarding'), ('submitted_for_review', 'Submitted for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('ready_to_publish', 'Ready to Publish'), ('published', 'Published'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='onboarding', max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=220)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='tenant-branding/logos/')),
                ('header_logo', models.ImageField(blank=True, upload_to='tenant-branding/header-logos/')),
                ('favicon', models.ImageField(blank=True, upload_to='tenant-branding/favicons/')),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_channel_url', models.URLField(blank=True)),
                ('live_tv_url', models.URLField(blank=True)),
                ('site_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
                ('organization_name', models.CharField(blank=True, max_length=180)),
                ('legal_notes', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_onboarding', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnboardingReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='subscriptions.tenantonboarding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_slug', models.SlugField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment Pending'), ('subscription_verified', 'Subscription Verified'), ('tenant_created', 'Tenant Created'), ('failed', 'Failed')], db_index=True, default='draft', max_length=40)),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('plan_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_acquisitions', to='subscriptions.planprice')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_acquisition', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_acquisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_5f2a64_idx'), models.Index(fields=['provider_subscription_id'], name='subscriptio_provide_d407ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('publication_slug',), name='unique_acquisition_publication_slug')],
            },
        ),
    ]
