# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_addon_currency_addon_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='razorpay_monthly_plan_id',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='razorpay_yearly_plan_id',
        ),
        migrations.RenameField(
            model_name='tenantaddon',
            old_name='provider_subscription_id',
            new_name='provider_payment_reference',
        ),
        migrations.RenameField(
            model_name='tenantsubscription',
            old_name='razorpay_subscription_id',
            new_name='razorpay_payment_reference',
        ),
        migrations.RenameField(
            model_name='customeracquisition',
            old_name='provider_subscription_id',
            new_name='provider_order_id',
        ),
        migrations.RemoveIndex(
            model_name='customeracquisition',
            name='subscriptio_provide_d407ba_idx',
        ),
        migrations.AddIndex(
            model_name='customeracquisition',
            index=models.Index(fields=['provider_order_id'], name='subscriptio_provide_e6ee97_idx'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='environment',
            field=models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=10),
        ),
        migrations.DeleteModel(
            name='RazorpayPlanMapping',
        ),
    ]
