# Generated by Codex on 2026-09-03

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_razorpay_recurring_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeracquisition',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeracquisition',
            name='provider_payload',
            field=core.fields.JSONTextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeracquisition',
            name='provider_receipt',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeracquisition',
            name='provider_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='customeracquisition',
            index=models.Index(fields=['provider_payment_id'], name='subscriptio_provide_4d5119_idx'),
        ),
        migrations.AddIndex(
            model_name='customeracquisition',
            index=models.Index(fields=['provider_receipt'], name='subscriptio_provide_0605bd_idx'),
        ),
    ]
