# Generated by Django 5.2.17 on 2026-09-04 18:20

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_planchangerequest_upgrade_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planchangerequest',
            name='provider_payload',
            field=core.fields.JSONTextField(blank=True),
        ),
    ]
