# Generated by Django 5.2.17 on 2026-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_onboardingautomationpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingautomationpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
