# Generated by Django 5.2.17 on 2026-09-05 03:58

from django.db import migrations, models


def create_default_support_contact(apps, schema_editor):
    PlatformSupportContact = apps.get_model('subscriptions', 'PlatformSupportContact')
    PlatformSupportContact.objects.get_or_create(
        name='Default Support',
        defaults={
            'support_email': 'shriinfowaveprivatelimited@gmail.com',
            'whatsapp_number': '918279408396',
            'business_hours': 'Monday to Saturday, 10:00 AM to 6:00 PM IST',
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_onboardingautomationpolicy_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSupportContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Support', max_length=120)),
                ('support_email', models.EmailField(default='shriinfowaveprivatelimited@gmail.com', max_length=254)),
                ('whatsapp_number', models.CharField(default='918279408396', max_length=20)),
                ('business_hours', models.CharField(default='Monday to Saturday, 10:00 AM to 6:00 PM IST', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.RunPython(create_default_support_contact, migrations.RunPython.noop),
    ]
