# Generated by Django 5.2.17 on 2026-09-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_platformsupportcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPurchaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Plan Purchase Agreement', max_length=180)),
                ('content', models.TextField()),
                ('checkbox_label', models.CharField(default='I have read and agree to the plan purchase terms.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
