# Generated by Django 5.2.17 on 2026-09-05 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_platformpurchaseagreement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_title', models.CharField(max_length=180)),
                ('agreement_content', models.TextField()),
                ('checkbox_label', models.CharField(max_length=255)),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('billing_months', models.PositiveIntegerField(default=1)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(db_index=True)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_agreement_acceptances', to='subscriptions.customeracquisition')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptances', to='subscriptions.platformpurchaseagreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_agreement_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'accepted_at'], name='subscriptio_user_id_f83c64_idx'), models.Index(fields=['acquisition', 'accepted_at'], name='subscriptio_acquisi_6ca19d_idx')],
            },
        ),
    ]
