# Generated by Django 5.2.17 on 2026-09-05 07:17

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_purchaseagreementacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='entitlement_snapshot',
            field=core.fields.JSONTextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='entitlement_snapshot',
            field=core.fields.JSONTextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='entitlement_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
