# Generated by Django 5.2.17 on 2026-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_gst_billing_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeracquisition',
            name='customer_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
