# Generated by Django 5.2.17 on 2026-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_customeracquisition_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantonboarding',
            name='header_banner',
            field=models.ImageField(blank=True, upload_to='tenant-branding/header-banners/'),
        ),
    ]
