# Generated by Django 5.2.17 on 2026-08-31 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('default_title', models.CharField(blank=True, max_length=255)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
                ('default_robots_index', models.BooleanField(default=True)),
                ('default_robots_follow', models.BooleanField(default=True)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('twitter_site', models.CharField(blank=True, max_length=80)),
                ('google_site_verification', models.CharField(blank=True, max_length=128)),
                ('bing_site_verification', models.CharField(blank=True, max_length=128)),
                ('google_analytics_id', models.CharField(blank=True, max_length=40)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_seo_settings_per_tenant')],
            },
        ),
    ]
