# Generated by Django 5.2.17 on 2026-08-31 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_covers', to='media_library.mediaasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media_library.photogallery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_items', to='media_library.mediaasset')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='photogallery',
            index=models.Index(fields=['tenant', 'is_published'], name='media_libra_tenant__25bcc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='photogallery',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_gallery_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='photogalleryitem',
            index=models.Index(fields=['tenant', 'gallery', 'order'], name='media_libra_tenant__b2f19c_idx'),
        ),
    ]
