# Generated by Django 5.2.17 on 2026-08-31 09:13

import core.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_photogallery_photogalleryitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(upload_to=core.security.safe_upload_name, validators=[core.security.validate_upload_file]),
        ),
    ]
